package com.mymusic.player.ui

import android.graphics.Bitmap
import android.graphics.Color
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.unit.dp
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter
import com.mymusic.player.network.QrLoginClient
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch

/**
 * Bilibili QR login: shows a QR generated by the official passport API; the user
 * scans it with the Bilibili app and confirms. On success the cookie is saved to
 * settings and the screen closes.
 */
@Composable
fun LoginScreen(vm: MainViewModel, onClose: () -> Unit) {
    val client = remember { QrLoginClient() }
    val scope = rememberCoroutineScope()

    var qr by remember { mutableStateOf<ImageBitmap?>(null) }
    var sessionKey by remember { mutableStateOf<String?>(null) }
    var status by remember { mutableStateOf("正在获取二维码…") }
    var error by remember { mutableStateOf<String?>(null) }
    var busy by remember { mutableStateOf(false) }

    suspend fun refreshQr() {
        busy = true
        error = null
        qr = null
        sessionKey = null
        status = "正在获取二维码…"
        try {
            val session = client.generate()
            qr = renderQr(session.url)
            sessionKey = session.key
            status = "请用哔哩哔哩 App 扫码"
        } catch (e: Exception) {
            error = e.message ?: "获取二维码失败，请检查网络"
            status = ""
        } finally {
            busy = false
        }
    }

    LaunchedEffect(Unit) { refreshQr() }

    // Poll while a QR is on screen.
    LaunchedEffect(sessionKey) {
        val key = sessionKey ?: return@LaunchedEffect
        while (isActive) {
            val result = runCatching { client.poll(key) }.getOrElse { null }
            when (result) {
                is QrLoginClient.Result.Success -> {
                    scope.launch { vm.saveCookie(result.cookie) }
                    vm.showMessage("登录成功，已保存 Cookie")
                    onClose()
                    return@LaunchedEffect
                }
                QrLoginClient.Result.Pending -> status = "请用哔哩哔哩 App 扫码"
                QrLoginClient.Result.Scanned -> status = "已扫码，请在手机上确认登录"
                QrLoginClient.Result.Expired -> {
                    status = "二维码已失效，请刷新"
                    return@LaunchedEffect
                }
                null -> {
                    error = "网络异常，请点击刷新重试"
                    status = ""
                    return@LaunchedEffect
                }
            }
            delay(2000)
        }
    }

    Column(
        Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text("扫码登录 B 站", style = MaterialTheme.typography.titleLarge)
        Spacer(Modifier.height(8.dp))
        Text(
            "用手机上的哔哩哔哩 App 扫描二维码并确认授权，即可自动获取 Cookie（解锁更高音质）。",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )

        Spacer(Modifier.height(20.dp))
        Box(
            Modifier
                .size(240.dp)
                .background(androidx.compose.ui.graphics.Color.White)
                .padding(12.dp),
            contentAlignment = Alignment.Center,
        ) {
            val qrImage = qr
            when {
                qrImage != null -> Image(
                    bitmap = qrImage,
                    contentDescription = "B 站登录二维码",
                    modifier = Modifier.fillMaxSize(),
                )
                busy -> CircularProgressIndicator()
                else -> Text(
                    error ?: "二维码加载中…",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(8.dp),
                )
            }
        }

        Spacer(Modifier.height(16.dp))
        Text(
            status,
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.primary,
        )
        error?.let {
            Spacer(Modifier.height(4.dp))
            Text(
                it,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.error,
            )
        }

        Spacer(Modifier.height(20.dp))
        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Button(
                onClick = { scope.launch { refreshQr() } },
                enabled = !busy,
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text("刷新二维码")
            }
            OutlinedButton(
                onClick = onClose,
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text("返回")
            }
        }
    }
}

/** Render [content] as a QR [ImageBitmap]. */
private fun renderQr(content: String, size: Int = 512): ImageBitmap? {
    return try {
        val hints = mapOf(EncodeHintType.MARGIN to 1)
        val matrix = QRCodeWriter().encode(content, BarcodeFormat.QR_CODE, size, size, hints)
        val pixels = IntArray(size * size)
        for (y in 0 until size) {
            for (x in 0 until size) {
                pixels[y * size + x] = if (matrix[x, y]) Color.BLACK else Color.WHITE
            }
        }
        Bitmap.createBitmap(size, size, Bitmap.Config.RGB_565)
            .apply { setPixels(pixels, 0, size, 0, 0, size, size) }
            .asImageBitmap()
    } catch (e: Exception) {
        null
    }
}
